---
# ------------------------------------------------
# RPM url
# ------------------------------------------------
code_server_version: "4.11.0"
code_server_rpm_url: >-
  https://gpte-public.s3.amazonaws.com/CI+Assets/Ansible+Automation+Controller+for+Advanced+Users/code-server-{{ code_server_version }}-amd64.rpm

# ------------------------------------------------
# Code server IP and Port
# ------------------------------------------------
code_server_bind_addr_ip: 0.0.0.0
code_server_bind_addr_port: 8080

# ------------------------------------------------
# Auth type none/password
# ------------------------------------------------
code_server_auth_type: password

# ------------------------------------------------
# User and password
# ------------------------------------------------
code_server_user_dir: "/home/{{ code_server_user_name }}/.local/share/code-server"
code_server_config_dir: "/home/{{ code_server_user_name }}/.config/code-server"
code_server_user_name: "{{ student_name }}"
code_user_password: "{{ common_password }}"
code_server_group_name: users

# ------------------------------------------------
# Code Server Extensions
# ------------------------------------------------
# base URL for default extensions, ending / is important!
code_server_base_extensions_url: https://gpte-public.s3.amazonaws.com/vscode-plugins/

# code_server_default_extensions: []
code_server_base_extensions:
  - ms-toolsai.vscode-jupyter-slideshow-0.1.5.vsix
  - ms-toolsai.vscode-jupyter-cell-tags-0.1.8.vsix
  - ms-toolsai.jupyter-keymap-1.1.0.vsix
  - ms-toolsai.jupyter-renderers-1.0.15.vsix
  - ms-toolsai.jupyter-2023.3.100.vsix
  - ms-python.python-2023.4.1.vsix
  - redhat.vscode-yaml-1.12.2.vsix
  - redhat.ansible-1.2.44.vsix

# Example
# code_server_extension_urls:
#   - https://github.com/ansible/workshops/raw/devel/files/bierner.markdown-preview-github-styles-0.1.6.vsix
#   - https://github.com/ansible/workshops/raw/devel/files/hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
#   - https://github.com/ansible/workshops/raw/devel/files/redhat.ansible-0.4.5.vsix

code_server_extension_urls: []

# ------------------------------------------------
# Code Server Additional settings
# ------------------------------------------------
code_server_additional_settings: |
  "files.exclude": {
    "**/.git": true,
    "**/.kube": true,
    "**/.bash*": true,
    "**/.vim*": true,
    "**/.ssh": true,
    "**/.vscode": true,
    "**/.local": true,
    "**/.config": true,
    "**/.ansible": true,
    "**/.cache": true },
  "security.workspace.trust.enabled": false

# ------------------------------------------------
# Code Server workspace setup
# ------------------------------------------------
# Define to create workspace
# code_server_user_workspace_path: "/home/{{ student_name }}"
# Define to clone repos
# code_server_user_workspace_repos:
#   - repo: "{{ controller_gitea_repo_url }}"
#     name: demo
#     branch: main
#   - repo: "{{ eda_gitea_repo_url }}"
#     name: eda-rulebooks
#     branch: main
